"""
Build DiffusionDrive training cache from Bench2Drive infos.

This script consumes the preprocessed Bench2Drive infos generated by PAD's
Bench2DriveZoo/bench2driveMMCV/datasets/prepare_B2D.py and writes cache files
compatible with DiffusionDrive's CacheOnlyDataset:

  {cache_root}/{train,val}/{token}/transfuser_feature.gz
  {cache_root}/{train,val}/{token}/transfuser_target.gz

It intentionally does not write NAVSIM PDM score targets. Bench2Drive needs a
separate scoring adapter; fake PDM labels would silently corrupt scorer/GRPO
training.
"""

from __future__ import annotations

import argparse
import gzip
import math
import multiprocessing as mp
import os
import pickle
import re
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import cv2
import numpy as np
import torch
from tqdm import tqdm


CAM_FRONT = "CAM_FRONT"
CAM_LEFT = "CAM_FRONT_LEFT"
CAM_RIGHT = "CAM_FRONT_RIGHT"

BEV_PIXEL_WIDTH = 256
BEV_PIXEL_HEIGHT = 128
BEV_PIXEL_SIZE = 0.25
LIDAR_MIN_X = -32.0
LIDAR_MAX_X = 32.0
LIDAR_MIN_Y = -32.0
LIDAR_MAX_Y = 32.0

NUM_BEV_CLASSES = 7
BEV_ROAD_LABEL = 1
BEV_CENTERLINE_LABEL = 3
BEV_STATIC_LABEL = 4
BEV_VEHICLE_LABEL = 5
BEV_PEDESTRIAN_LABEL = 6
B2D_WRONG_DIRECTION_DISABLED_SCENARIOS = (
    "Accident",
    "AccidentTwoWays",
    "ConstructionObstacle",
    "ConstructionObstacleTwoWays",
    "ParkedObstacle",
    "ParkedObstacleTwoWays",
    "HazardAtSideLane",
    "HazardAtSideLaneTwoWays",
    "VehicleOpensDoorTwoWays",
)

B2D_NON_COLLIDABLE_STATIC_KEYWORDS = (
    "traffic_light",
    "traffic.speed_limit",
    "traffic.stop",
    "speed_limit",
)
B2D_COLLIDABLE_STATIC_KEYWORDS = (
    "barrier",
    "box",
    "cone",
    "construction",
    "debris",
    "obstacle",
    "trafficwarning",
    "warning",
)

_WORKER_INFOS = None
_WORKER_MAP_INFOS = None
_WORKER_ARGS = None
_WORKER_SPLIT = None
_WORKER_B2D_ROOT = None
_WORKER_CACHE_ROOT = None


def dump_feature_target_to_pickle(path: Path, data_dict: Dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with gzip.open(path, "wb", compresslevel=1) as f:
        pickle.dump(data_dict, f)


def load_pickle(path: Path):
    with open(path, "rb") as f:
        return pickle.load(f)


def load_route_scenarios(path: Optional[Path]) -> Dict[str, str]:
    if path is None or not path.is_file():
        return {}
    tree = ET.parse(str(path))
    out: Dict[str, str] = {}
    for route in tree.getroot().findall("route"):
        route_id = str(route.get("id", "")).strip()
        scenarios = route.find("scenarios")
        scenario = scenarios.find("scenario") if scenarios is not None else None
        if route_id and scenario is not None:
            out[route_id] = str(scenario.get("type", "")).strip()
    return out


def extract_route_id(folder: object) -> Optional[str]:
    match = re.search(r"Route[_-]?(\d+)", str(folder))
    if match is None:
        return None
    return str(int(match.group(1)))


def infer_wrong_direction_enabled(info: Dict[str, object], args: argparse.Namespace) -> Tuple[bool, str]:
    scenario_by_route = getattr(args, "route_scenario_by_id", {}) or {}
    disabled = set(getattr(args, "wrong_direction_disabled_scenarios", ()) or ())
    route_id = extract_route_id(info.get("folder", ""))
    scenario_type = scenario_by_route.get(route_id, "") if route_id is not None else ""
    if scenario_type and scenario_type in disabled:
        return False, scenario_type
    return True, scenario_type


def normalize_angle(angle: float) -> float:
    return float((angle + math.pi) % (2.0 * math.pi) - math.pi)


def b2d_xy_to_diffusiondrive(xy: np.ndarray) -> np.ndarray:
    """Convert PAD/B2D lidar XY (right, front) to DiffusionDrive XY (front, left)."""
    arr = np.asarray(xy, dtype=np.float32)
    out = np.empty_like(arr, dtype=np.float32)
    out[..., 0] = arr[..., 1]
    out[..., 1] = -arr[..., 0]
    return out


def b2d_yaw_to_diffusiondrive(yaw: float) -> float:
    """Convert heading from PAD/B2D lidar frame to DiffusionDrive local frame."""
    return normalize_angle(float(yaw) - math.pi / 2.0)


def safe_token(split: str, idx: int, info: Dict[str, object]) -> str:
    folder = str(info.get("folder", "unknown")).replace("\\", "/")
    folder = folder.strip("/").replace("/", "_")
    frame_idx = int(info.get("frame_idx", idx))
    return f"{split}_{idx:08d}_{folder}_{frame_idx:05d}"


def is_same_log(a: Dict[str, object], b: Dict[str, object]) -> bool:
    return str(a.get("folder", "")) == str(b.get("folder", ""))


def b2d_box_heading_to_local(box: np.ndarray) -> float:
    # prepare_B2D stores yaw in LiDARInstance3DBoxes convention.
    return normalize_angle(-float(box[6] + math.pi / 2.0))


def classify_b2d_object(raw_name: object) -> str:
    name = str(raw_name)
    low = name.lower()
    if "walker.pedestrian" in low or "pedestrian" in low:
        return "pedestrian"
    if "vehicle" in low or "parkedvehicles" in low:
        return "vehicle"
    if "traffic_light" in low or "traffic.speed_limit" in low or "traffic.stop" in low:
        return "static"
    if "constructioncone" in low or "trafficwarning" in low or "warning" in low:
        return "static"
    return "static"


def is_b2d_non_collidable_static_object(raw_name: object) -> bool:
    low = str(raw_name).lower()
    return any(keyword in low for keyword in B2D_NON_COLLIDABLE_STATIC_KEYWORDS)


def is_b2d_collidable_static_object(raw_name: object) -> bool:
    """Return whether a static annotation should be treated as a physical obstacle."""
    if classify_b2d_object(raw_name) != "static":
        return False
    if is_b2d_non_collidable_static_object(raw_name):
        return False
    low = str(raw_name).lower()
    return any(keyword in low for keyword in B2D_COLLIDABLE_STATIC_KEYWORDS)

def coords_to_cv_pixels(coords: np.ndarray) -> np.ndarray:
    pixel_center = np.array([[0.0, BEV_PIXEL_WIDTH / 2.0]], dtype=np.float32)
    coords_idcs = (coords / BEV_PIXEL_SIZE) + pixel_center
    return np.round(coords_idcs).astype(np.int32)


def cv_mask_to_bev(mask: np.ndarray) -> np.ndarray:
    return np.rot90(mask)[::-1]


def box_corners_xy(x: float, y: float, length: float, width: float, heading: float) -> np.ndarray:
    half_l = float(length) / 2.0
    half_w = float(width) / 2.0
    corners = np.array(
        [[half_l, half_w], [-half_l, half_w], [-half_l, -half_w], [half_l, -half_w]],
        dtype=np.float32,
    )
    c = math.cos(float(heading))
    s = math.sin(float(heading))
    rot = np.array([[c, -s], [s, c]], dtype=np.float32)
    return corners @ rot.T + np.array([x, y], dtype=np.float32)


def rasterize_box(mask: np.ndarray, box_state: Sequence[float], value: float) -> None:
    x, y, heading, length, width = [float(v) for v in box_state]
    corners = box_corners_xy(x=x, y=y, length=length, width=width, heading=heading)
    exterior = coords_to_cv_pixels(corners.reshape(-1, 1, 2))
    cv2.fillPoly(mask, [exterior], color=float(value))


def read_rgb(path: Path) -> np.ndarray:
    image = cv2.imread(str(path), cv2.IMREAD_COLOR)
    if image is None:
        raise FileNotFoundError(str(path))
    return cv2.cvtColor(image, cv2.COLOR_BGR2RGB)


def resize_camera(image: np.ndarray, size: Tuple[int, int]) -> np.ndarray:
    return cv2.resize(image, size, interpolation=cv2.INTER_AREA)


def crop_front_stitch_patch(
    image: np.ndarray,
    keep_width: Optional[float] = None,
    horizontal_anchor: str = "center",
    start_x: Optional[int] = None,
) -> np.ndarray:
    height, width = image.shape[:2]
    # NAVSIM removes about 11% vertically before stitching.
    crop_y = int(round(height * (28.0 / 256.0)))
    if crop_y > 0 and height > 2 * crop_y:
        image = image[crop_y:-crop_y]
    if keep_width is None:
        return image
    keep_w = int(round(width * keep_width))
    keep_w = max(1, min(width, keep_w))
    if start_x is not None:
        x0 = int(start_x)
    elif horizontal_anchor == "left":
        x0 = 0
    elif horizontal_anchor == "right":
        x0 = max(0, width - keep_w)
    else:
        x0 = max(0, (width - keep_w) // 2)
    x0 = max(0, min(x0, width - keep_w))
    return image[:, x0 : x0 + keep_w]


def build_camera_feature(
    info: Dict[str, object],
    b2d_root: Path,
    stitch_mode: str,
    side_crop_ratio: float,
    side_overlap_ratio: float,
) -> torch.Tensor:
    sensors = info["sensors"]
    images = {}
    for cam in (CAM_LEFT, CAM_FRONT, CAM_RIGHT):
        rel_path = Path(str(sensors[cam]["data_path"]))
        images[cam] = read_rgb(b2d_root / rel_path)

    if stitch_mode == "front_only":
        stitched = crop_front_stitch_patch(images[CAM_FRONT], keep_width=None)
    else:
        front = crop_front_stitch_patch(images[CAM_FRONT], keep_width=None)
        if stitch_mode == "navsim_center":
            left = crop_front_stitch_patch(images[CAM_LEFT], keep_width=side_crop_ratio, horizontal_anchor="center")
            right = crop_front_stitch_patch(images[CAM_RIGHT], keep_width=side_crop_ratio, horizontal_anchor="center")
        elif stitch_mode == "b2d_inner":
            # B2D front-left/right cameras point diagonally. The inner image edge is
            # closest to the front camera, so it produces a less discontinuous panorama.
            left = crop_front_stitch_patch(images[CAM_LEFT], keep_width=side_crop_ratio, horizontal_anchor="right")
            right = crop_front_stitch_patch(images[CAM_RIGHT], keep_width=side_crop_ratio, horizontal_anchor="left")
        elif stitch_mode == "b2d_outer":
            # Use the outer side-camera regions to add lateral context instead of
            # duplicating the front camera overlap.
            left = crop_front_stitch_patch(images[CAM_LEFT], keep_width=side_crop_ratio, horizontal_anchor="left")
            right = crop_front_stitch_patch(images[CAM_RIGHT], keep_width=side_crop_ratio, horizontal_anchor="right")
        elif stitch_mode == "b2d_mid":
            # Skip the inner overlap with CAM_FRONT, then take the adjacent middle
            # band from the side cameras. This avoids both front duplication and
            # extreme outer-edge crops.
            left_w = images[CAM_LEFT].shape[1]
            right_w = images[CAM_RIGHT].shape[1]
            left_keep = max(1, int(round(left_w * side_crop_ratio)))
            right_keep = max(1, int(round(right_w * side_crop_ratio)))
            left_overlap = max(0, int(round(left_w * side_overlap_ratio)))
            right_overlap = max(0, int(round(right_w * side_overlap_ratio)))
            left = crop_front_stitch_patch(
                images[CAM_LEFT],
                keep_width=side_crop_ratio,
                start_x=left_w - left_overlap - left_keep,
            )
            right = crop_front_stitch_patch(
                images[CAM_RIGHT],
                keep_width=side_crop_ratio,
                start_x=right_overlap,
            )
        else:
            raise ValueError(f"Unsupported camera stitch mode: {stitch_mode}")
        stitched = np.concatenate([left, front, right], axis=1)
    stitched = resize_camera(stitched, (1024, 256))
    stitched = stitched.astype(np.float32) / 255.0
    return torch.from_numpy(stitched).permute(2, 0, 1).contiguous()


def b2d_lidar_path(info: Dict[str, object], b2d_root: Path) -> Path:
    lidar_sensor = info.get("sensors", {}).get("LIDAR_TOP", {})
    data_path = lidar_sensor.get("data_path") if isinstance(lidar_sensor, dict) else None
    if data_path:
        return b2d_root / Path(str(data_path))
    folder = str(info.get("folder", "")).strip("/")
    frame_idx = int(info.get("frame_idx", 0))
    return b2d_root / folder / "lidar" / f"{frame_idx:05d}.laz"


def read_b2d_lidar_xyz(path: Path) -> np.ndarray:
    try:
        import laspy
    except ImportError as exc:
        raise ImportError(
            "Reading Bench2Drive .laz lidar requires laspy and a LAZ backend. "
            "Install with: python -m pip install laspy lazrs"
        ) from exc

    try:
        return np.asarray(laspy.read(str(path)).xyz, dtype=np.float32)
    except Exception as exc:
        raise RuntimeError(
            f"Failed to read Bench2Drive lidar file {path}. "
            "If this is a compressed .laz file, install lazrs or laszip."
        ) from exc


def build_lidar_feature(
    info: Dict[str, object],
    b2d_root: Path,
    mode: str,
    coordinate_mode: str,
    height_mode: str,
    pixels_per_meter: float,
    hist_max_per_pixel: float,
    max_height_lidar: float,
    lidar_split_height: float,
    auto_min_points: int,
) -> torch.Tensor:
    if mode == "zeros":
        return torch.zeros((1, 256, 256), dtype=torch.float32)
    if mode != "histogram":
        raise ValueError(f"Unsupported lidar mode: {mode}")

    lidar_path = b2d_lidar_path(info, b2d_root)
    if not lidar_path.is_file():
        raise FileNotFoundError(f"Missing Bench2Drive lidar: {lidar_path}")

    xyz = read_b2d_lidar_xyz(lidar_path)
    if xyz.ndim != 2 or xyz.shape[1] < 3:
        return torch.zeros((1, 256, 256), dtype=torch.float32)

    points = xyz[:, :3].astype(np.float32, copy=False)
    points = points[np.isfinite(points).all(axis=1)]
    if points.size == 0:
        return torch.zeros((1, 256, 256), dtype=torch.float32)

    if coordinate_mode == "b2d_lidar":
        # Bench2Drive's visualization script uses (x, y) -> (y, -x) for its
        # own BEV display convention, but this can be 90 degrees off from the
        # prepared info boxes depending on which exported .laz frame is used.
        xy = b2d_xy_to_diffusiondrive(points[:, :2])
    elif coordinate_mode == "front_left":
        # Raw Bench2Drive .laz points are commonly stored as x=front, y=right;
        # DiffusionDrive uses x=front, y=left.
        xy = np.stack([points[:, 0], -points[:, 1]], axis=1).astype(np.float32)
    elif coordinate_mode == "identity":
        xy = points[:, :2].astype(np.float32, copy=True)
    else:
        raise ValueError(f"Unsupported lidar coordinate mode: {coordinate_mode}")
    point_cloud = np.concatenate([xy, points[:, 2:3]], axis=1)
    point_cloud = point_cloud[point_cloud[:, 2] < float(max_height_lidar)]

    above = point_cloud[point_cloud[:, 2] > float(lidar_split_height)]
    if height_mode == "above":
        point_cloud = above
    elif height_mode == "all":
        pass
    elif height_mode == "auto":
        if above.shape[0] >= int(auto_min_points):
            point_cloud = above
    else:
        raise ValueError(f"Unsupported lidar height mode: {height_mode}")

    xbins = np.linspace(
        LIDAR_MIN_X,
        LIDAR_MAX_X,
        int((LIDAR_MAX_X - LIDAR_MIN_X) * float(pixels_per_meter)) + 1,
    )
    ybins = np.linspace(
        LIDAR_MIN_Y,
        LIDAR_MAX_Y,
        int((LIDAR_MAX_Y - LIDAR_MIN_Y) * float(pixels_per_meter)) + 1,
    )
    hist = np.histogramdd(point_cloud[:, :2], bins=(xbins, ybins))[0].astype(np.float32)
    hist = np.clip(hist, 0.0, float(hist_max_per_pixel)) / float(hist_max_per_pixel)
    return torch.from_numpy(hist[None]).contiguous()


def b2d_command_to_navsim_4d(command: object) -> np.ndarray:
    # CARLA/B2D commonly uses: 1 left, 2 right, 3 straight, 4 lane_follow,
    # 5 change-left, 6 change-right. We map to [left, straight, right, follow].
    out = np.zeros(4, dtype=np.float32)
    try:
        cmd = int(command)
    except Exception:
        cmd = 4
    if cmd in (1, 5):
        out[0] = 1.0
    elif cmd == 3:
        out[1] = 1.0
    elif cmd in (2, 6):
        out[2] = 1.0
    else:
        out[3] = 1.0
    return out


def build_status_feature(info: Dict[str, object]) -> torch.Tensor:
    command = b2d_command_to_navsim_4d(info.get("command_near", 4))
    ego_vel = np.asarray(info.get("ego_vel", np.zeros(3)), dtype=np.float32)[:2]
    ego_accel = np.asarray(info.get("ego_accel", np.zeros(3)), dtype=np.float32)[:2]
    ego_vel = np.nan_to_num(ego_vel, nan=0.0, posinf=0.0, neginf=0.0)
    ego_accel = np.nan_to_num(ego_accel, nan=0.0, posinf=0.0, neginf=0.0)
    status = np.concatenate([command, ego_vel, ego_accel], axis=0).astype(np.float32)
    return torch.from_numpy(status)


def pose_in_current_lidar(cur_info: Dict[str, object], adj_info: Dict[str, object]) -> np.ndarray:
    cur_world2lidar = np.asarray(cur_info["sensors"]["LIDAR_TOP"]["world2lidar"], dtype=np.float64)
    adj_world2lidar = np.asarray(adj_info["sensors"]["LIDAR_TOP"]["world2lidar"], dtype=np.float64)
    adj_lidar2world = np.linalg.inv(adj_world2lidar)
    adj2cur = cur_world2lidar @ adj_lidar2world
    xy = b2d_xy_to_diffusiondrive(adj2cur[:2, 3].astype(np.float32))
    yaw = normalize_angle(float(adj_info.get("ego_yaw", 0.0)) - float(cur_info.get("ego_yaw", 0.0)))
    return np.array([xy[0], xy[1], yaw], dtype=np.float32)


def build_ego_history(
    infos: Sequence[Dict[str, object]],
    idx: int,
    sample_interval: int,
    history_frames: int,
) -> torch.Tensor:
    cur_info = infos[idx]
    poses: List[np.ndarray] = []
    first_idx = idx - (history_frames - 1) * sample_interval
    for adj_idx in range(first_idx, idx + 1, sample_interval):
        if 0 <= adj_idx < len(infos) and is_same_log(cur_info, infos[adj_idx]):
            poses.append(pose_in_current_lidar(cur_info, infos[adj_idx]))
        else:
            poses.append(np.array([np.nan, np.nan, np.nan], dtype=np.float32))

    valid = [pose for pose in poses if np.isfinite(pose).all()]
    fill = valid[0] if valid else np.zeros(3, dtype=np.float32)
    poses = [pose if np.isfinite(pose).all() else fill.copy() for pose in poses]
    poses[-1] = np.zeros(3, dtype=np.float32)
    return torch.from_numpy(np.stack(poses, axis=0).astype(np.float32))


def build_future_trajectory(
    infos: Sequence[Dict[str, object]],
    idx: int,
    sample_interval: int,
    future_frames: int,
    max_translation_m: float = 120.0,
    max_step_m: float = 60.0,
) -> Optional[torch.Tensor]:
    cur_info = infos[idx]
    poses: List[np.ndarray] = []
    for step in range(1, future_frames + 1):
        adj_idx = idx + step * sample_interval
        if adj_idx >= len(infos) or not is_same_log(cur_info, infos[adj_idx]):
            return None
        poses.append(pose_in_current_lidar(cur_info, infos[adj_idx]))
    trajectory = np.stack(poses, axis=0).astype(np.float32)
    if not np.isfinite(trajectory).all():
        return None
    if max_translation_m > 0.0:
        if float(np.linalg.norm(trajectory[:, :2], axis=-1).max()) > float(max_translation_m):
            return None
    if max_step_m > 0.0 and trajectory.shape[0] > 1:
        step = np.linalg.norm(trajectory[1:, :2] - trajectory[:-1, :2], axis=-1)
        if float(step.max()) > float(max_step_m):
            return None
    return torch.from_numpy(trajectory)


def in_lidar_range(x: float, y: float) -> bool:
    return LIDAR_MIN_X <= x <= LIDAR_MAX_X and LIDAR_MIN_Y <= y <= LIDAR_MAX_Y


def current_box_states_b2d_with_ids(
    info: Dict[str, object],
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, bool]:
    boxes = np.asarray(info.get("gt_boxes", np.zeros((0, 9))), dtype=np.float32)
    names = np.asarray(info.get("gt_names", []), dtype=object)
    num_points = np.asarray(info.get("num_points", np.ones((len(boxes),))), dtype=np.float32)
    raw_ids = info.get("gt_ids")
    stable_ids = raw_ids is not None
    ids = np.asarray(raw_ids if raw_ids is not None else np.arange(len(boxes)), dtype=object)
    if boxes.size == 0:
        return (
            np.zeros((0, 5), dtype=np.float32),
            np.asarray([], dtype=object),
            np.zeros((0, 2), dtype=np.float32),
            np.asarray([], dtype=object),
            stable_ids,
        )
    if boxes.ndim == 1:
        boxes = boxes.reshape(1, -1)
    if names.shape[0] != boxes.shape[0]:
        names = np.asarray(["unknown"] * boxes.shape[0], dtype=object)
    if num_points.shape[0] != boxes.shape[0]:
        num_points = np.ones((boxes.shape[0],), dtype=np.float32)
    if ids.shape[0] != boxes.shape[0]:
        stable_ids = False
        ids = np.asarray(np.arange(boxes.shape[0]), dtype=object)
    valid = num_points != 0
    boxes = boxes[valid]
    names = names[valid]
    ids = ids[valid]
    states = []
    velocities = []
    for box in boxes:
        x, y = float(box[0]), float(box[1])
        heading = b2d_box_heading_to_local(box)
        width = float(box[3])
        length = float(box[4])
        states.append([x, y, heading, length, width])
        if box.shape[0] >= 9:
            velocities.append([float(box[7]), float(box[8])])
        else:
            velocities.append([0.0, 0.0])
    return (
        np.asarray(states, dtype=np.float32),
        names,
        np.asarray(velocities, dtype=np.float32),
        ids,
        stable_ids,
    )


def current_box_states_b2d(info: Dict[str, object]) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    states, names, velocities, _, _ = current_box_states_b2d_with_ids(info)
    return states, names, velocities


def b2d_box_states_to_diffusiondrive(
    states: np.ndarray,
    velocities: np.ndarray,
) -> Tuple[np.ndarray, np.ndarray]:
    if len(states) == 0:
        return states.astype(np.float32, copy=False), velocities.astype(np.float32, copy=False)
    converted = states.astype(np.float32, copy=True)
    converted[:, :2] = b2d_xy_to_diffusiondrive(converted[:, :2])
    converted[:, 2] = np.asarray(
        [b2d_yaw_to_diffusiondrive(float(yaw)) for yaw in converted[:, 2]],
        dtype=np.float32,
    )
    return converted, b2d_xy_to_diffusiondrive(velocities)


def current_box_states(info: Dict[str, object]) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    states, names, velocities = current_box_states_b2d(info)
    states, velocities = b2d_box_states_to_diffusiondrive(states, velocities)
    return states, names, velocities


def transform_box_states_to_current(
    source_info: Dict[str, object],
    current_info: Dict[str, object],
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    states, names, velocities, _, _ = transform_box_records_to_current(source_info, current_info)
    return states, names, velocities


def transform_box_records_to_current(
    source_info: Dict[str, object],
    current_info: Dict[str, object],
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, bool]:
    states, names, velocities, ids, stable_ids = current_box_states_b2d_with_ids(source_info)
    if len(states) == 0:
        return states, names, velocities, ids, stable_ids
    if source_info is current_info:
        states, velocities = b2d_box_states_to_diffusiondrive(states, velocities)
        return states, names, velocities, ids, stable_ids

    cur_world2lidar = np.asarray(current_info["sensors"]["LIDAR_TOP"]["world2lidar"], dtype=np.float64)
    src_world2lidar = np.asarray(source_info["sensors"]["LIDAR_TOP"]["world2lidar"], dtype=np.float64)
    src2cur = cur_world2lidar @ np.linalg.inv(src_world2lidar)
    yaw_delta = math.atan2(float(src2cur[1, 0]), float(src2cur[0, 0]))
    transformed = states.copy()
    for i, state in enumerate(states):
        point = np.array([state[0], state[1], 0.0, 1.0], dtype=np.float64)
        point_cur = src2cur @ point
        transformed[i, 0] = float(point_cur[0])
        transformed[i, 1] = float(point_cur[1])
        transformed[i, 2] = normalize_angle(float(state[2]) + yaw_delta)
    velocities = (src2cur[:2, :2] @ velocities.T).T.astype(np.float32)
    transformed, velocities = b2d_box_states_to_diffusiondrive(transformed, velocities)
    return transformed, names, velocities, ids, stable_ids


def diffusiondrive_lidar2world(info: Dict[str, object]) -> np.ndarray:
    """Return a transform from DiffusionDrive local XY (front, left) to B2D world."""
    b2d_world2lidar = np.asarray(info["sensors"]["LIDAR_TOP"]["world2lidar"], dtype=np.float32)
    b2d_lidar2world = np.linalg.inv(b2d_world2lidar).astype(np.float32)
    dd_lidar_to_b2d_lidar = np.eye(4, dtype=np.float32)
    dd_lidar_to_b2d_lidar[0, 0] = 0.0
    dd_lidar_to_b2d_lidar[0, 1] = -1.0
    dd_lidar_to_b2d_lidar[1, 0] = 1.0
    dd_lidar_to_b2d_lidar[1, 1] = 0.0
    return (b2d_lidar2world @ dd_lidar_to_b2d_lidar).astype(np.float32)


def build_future_agent_boxes(
    infos: Sequence[Dict[str, object]],
    idx: int,
    sample_interval: int,
    future_frames: int,
    max_future_agents: int,
    range_m: float,
) -> Tuple[torch.Tensor, torch.Tensor]:
    current_info = infos[idx]
    records: Dict[str, Dict[str, object]] = {}

    current_states, current_names, _, current_ids, current_stable_ids = transform_box_records_to_current(
        current_info,
        current_info,
    )
    current_order = (
        np.argsort(np.linalg.norm(current_states[:, :2], axis=-1))
        if len(current_states)
        else []
    )
    for rank in current_order:
        state = current_states[int(rank)]
        name = current_names[int(rank)]
        if not is_b2d_collidable_static_object(name):
            continue
        corners = box_corners_xy(
            x=float(state[0]),
            y=float(state[1]),
            length=float(state[3]),
            width=float(state[4]),
            heading=float(state[2]),
        ).astype(np.float32)
        center = corners.mean(axis=0)
        if range_m > 0 and not (
            abs(float(center[0])) <= range_m
            and abs(float(center[1])) <= range_m
        ):
            continue
        key = (
            f"static:id:{current_ids[int(rank)]}"
            if current_stable_ids
            else f"static:rank:{rank}"
        )
        records[key] = {
            "corners": [corners for _ in range(future_frames)],
            "min_dist": float(np.linalg.norm(center)),
        }

    for step in range(1, future_frames + 1):
        adj_idx = idx + step * sample_interval
        if adj_idx >= len(infos) or not is_same_log(current_info, infos[adj_idx]):
            continue
        states, names, _, ids, stable_ids = transform_box_records_to_current(infos[adj_idx], current_info)
        order = np.argsort(np.linalg.norm(states[:, :2], axis=-1)) if len(states) else []
        for rank in order:
            state = states[int(rank)]
            name = names[int(rank)]
            if classify_b2d_object(name) not in ("vehicle", "pedestrian"):
                continue
            corners = box_corners_xy(
                x=float(state[0]),
                y=float(state[1]),
                length=float(state[3]),
                width=float(state[4]),
                heading=float(state[2]),
            ).astype(np.float32)
            center = corners.mean(axis=0)
            if range_m > 0 and not (
                abs(float(center[0])) <= range_m
                and abs(float(center[1])) <= range_m
            ):
                continue
            key = f"id:{ids[int(rank)]}" if stable_ids else f"step:{step}:rank:{rank}"
            if key not in records:
                records[key] = {
                    "corners": [None for _ in range(future_frames)],
                    "min_dist": float(np.linalg.norm(center)),
                }
            records[key]["corners"][step - 1] = corners
            records[key]["min_dist"] = min(float(records[key]["min_dist"]), float(np.linalg.norm(center)))

    selected = sorted(records.values(), key=lambda item: float(item["min_dist"]))[:max_future_agents]
    boxes = np.zeros((max_future_agents, future_frames, 4, 2), dtype=np.float32)
    mask = np.zeros((max_future_agents, future_frames), dtype=bool)
    for agent_idx, record in enumerate(selected):
        for step_idx, corners in enumerate(record["corners"]):
            if corners is None:
                continue
            boxes[agent_idx, step_idx] = corners
            mask[agent_idx, step_idx] = True
    return torch.from_numpy(boxes), torch.from_numpy(mask)


def build_agent_targets(info: Dict[str, object], max_agents: int = 30) -> Tuple[torch.Tensor, torch.Tensor]:
    states, names, _ = current_box_states(info)
    vehicle_states = []
    for state, name in zip(states, names):
        if classify_b2d_object(name) != "vehicle":
            continue
        if not in_lidar_range(float(state[0]), float(state[1])):
            continue
        vehicle_states.append(state)

    agent_states = np.zeros((max_agents, 5), dtype=np.float32)
    agent_labels = np.zeros((max_agents,), dtype=bool)
    if vehicle_states:
        arr = np.asarray(vehicle_states, dtype=np.float32)
        order = np.argsort(np.linalg.norm(arr[:, :2], axis=-1))[:max_agents]
        arr = arr[order]
        agent_states[: len(arr)] = arr
        agent_labels[: len(arr)] = True
    return torch.from_numpy(agent_states), torch.from_numpy(agent_labels)


def localize_map_points(points: np.ndarray, world2lidar: np.ndarray) -> np.ndarray:
    points = np.asarray(points, dtype=np.float32)
    if points.ndim != 2 or points.shape[0] < 1:
        return np.zeros((0, 2), dtype=np.float32)
    if points.shape[1] == 2:
        z = np.zeros((points.shape[0], 1), dtype=np.float32)
        points = np.concatenate([points, z], axis=1)
    homo = np.concatenate([points[:, :3], np.ones((points.shape[0], 1), dtype=np.float32)], axis=1)
    local = (world2lidar @ homo.T).T
    return b2d_xy_to_diffusiondrive(local[:, :2].astype(np.float32))


def localize_world_xy(points_xy: np.ndarray, info: Dict[str, object]) -> np.ndarray:
    world2lidar = np.asarray(info["sensors"]["LIDAR_TOP"]["world2lidar"], dtype=np.float32)
    return localize_map_points(points_xy, world2lidar)


def bev_to_cv_mask(mask: np.ndarray) -> np.ndarray:
    return np.rot90(mask[::-1], k=-1)


def local_points_in_window(
    local: np.ndarray,
    front_min: float,
    front_max: float,
    lateral_abs: float,
) -> bool:
    if local.shape[0] == 0:
        return False
    return bool(
        (
            (local[:, 0] >= front_min)
            & (local[:, 0] <= front_max)
            & (np.abs(local[:, 1]) <= lateral_abs)
        ).any()
    )


def draw_polyline(mask: np.ndarray, points_xy: np.ndarray, value: int, thickness: int) -> None:
    if points_xy.shape[0] < 2:
        return
    if not (
        ((points_xy[:, 0] >= LIDAR_MIN_X) & (points_xy[:, 0] <= LIDAR_MAX_X))
        & ((points_xy[:, 1] >= LIDAR_MIN_Y) & (points_xy[:, 1] <= LIDAR_MAX_Y))
    ).any():
        return
    pts = coords_to_cv_pixels(points_xy.reshape(-1, 1, 2))
    cv2.polylines(mask, [pts], isClosed=False, color=int(value), thickness=int(thickness))


def draw_polygon(mask: np.ndarray, points_xy: np.ndarray, value: int) -> None:
    if points_xy.shape[0] < 3:
        return
    if not (
        ((points_xy[:, 0] >= LIDAR_MIN_X) & (points_xy[:, 0] <= LIDAR_MAX_X))
        & ((points_xy[:, 1] >= LIDAR_MIN_Y) & (points_xy[:, 1] <= LIDAR_MAX_Y))
    ).any():
        return
    pts = coords_to_cv_pixels(points_xy.reshape(-1, 1, 2))
    cv2.fillPoly(mask, [pts], color=int(value))


def build_static_map_bev(info: Dict[str, object], map_infos: Dict[str, object]) -> np.ndarray:
    town_name = str(info.get("town_name", ""))
    map_info = map_infos.get(town_name)
    bev = np.zeros((BEV_PIXEL_HEIGHT, BEV_PIXEL_WIDTH), dtype=np.int64)
    if map_info is None:
        return bev

    world2lidar = np.asarray(info["sensors"]["LIDAR_TOP"]["world2lidar"], dtype=np.float32)
    road_cv = np.zeros((BEV_PIXEL_WIDTH, BEV_PIXEL_HEIGHT), dtype=np.uint8)
    center_cv = np.zeros((BEV_PIXEL_WIDTH, BEV_PIXEL_HEIGHT), dtype=np.uint8)

    road_thickness = max(3, int(round(6.0 / BEV_PIXEL_SIZE)))
    line_thickness = max(1, int(round(0.5 / BEV_PIXEL_SIZE)))
    lane_points = map_info.get("lane_points", [])
    lane_types = map_info.get("lane_types", [])
    for points, lane_type in zip(lane_points, lane_types):
        local = localize_map_points(points, world2lidar)
        lane_type = str(lane_type)
        if lane_type in ("Broken", "Solid", "SolidSolid", "Center"):
            draw_polyline(road_cv, local, value=255, thickness=road_thickness)
        if lane_type == "Center":
            draw_polyline(center_cv, local, value=255, thickness=line_thickness)

    road = cv_mask_to_bev(road_cv) > 0
    center = cv_mask_to_bev(center_cv) > 0
    bev[road] = BEV_ROAD_LABEL
    bev[center] = BEV_CENTERLINE_LABEL
    return bev


def build_lane_direction_bev(
    info: Dict[str, object],
    map_infos: Dict[str, object],
    radius_m: float,
    search_radius: float,
) -> Tuple[torch.Tensor, torch.Tensor]:
    town_name = str(info.get("town_name", ""))
    map_info = map_infos.get(town_name)
    direction_x = np.zeros((BEV_PIXEL_WIDTH, BEV_PIXEL_HEIGHT), dtype=np.float32)
    direction_y = np.zeros((BEV_PIXEL_WIDTH, BEV_PIXEL_HEIGHT), dtype=np.float32)
    counts = np.zeros((BEV_PIXEL_WIDTH, BEV_PIXEL_HEIGHT), dtype=np.float32)
    if map_info is None:
        empty_dir = np.zeros((2, BEV_PIXEL_HEIGHT, BEV_PIXEL_WIDTH), dtype=np.float32)
        return torch.from_numpy(empty_dir), torch.zeros((BEV_PIXEL_HEIGHT, BEV_PIXEL_WIDTH), dtype=torch.bool)

    world2lidar = np.asarray(info["sensors"]["LIDAR_TOP"]["world2lidar"], dtype=np.float32)
    radius_px = max(0, int(round(radius_m / BEV_PIXEL_SIZE)))
    lane_points = map_info.get("lane_points", [])
    lane_sample_points = map_info.get("lane_sample_points", [])
    lane_types = map_info.get("lane_types", [])
    for lane_idx, (points, lane_type) in enumerate(zip(lane_points, lane_types)):
        if str(lane_type) != "Center":
            continue
        sample_points = lane_sample_points[lane_idx] if lane_idx < len(lane_sample_points) else points
        sample_local = localize_map_points(sample_points, world2lidar)
        if not local_points_in_window(sample_local, front_min=-5.0, front_max=search_radius, lateral_abs=search_radius):
            continue
        local = localize_map_points(points, world2lidar)
        if local.shape[0] < 2:
            continue
        for p0, p1 in zip(local[:-1], local[1:]):
            delta = p1 - p0
            length = float(np.linalg.norm(delta))
            if length < 1e-3:
                continue
            tangent = delta / length
            num_samples = max(2, int(math.ceil(length / BEV_PIXEL_SIZE)))
            ratio = np.linspace(0.0, 1.0, num_samples, dtype=np.float32)
            samples = p0[None] + ratio[:, None] * delta[None]
            pix = coords_to_cv_pixels(samples.reshape(-1, 1, 2)).reshape(-1, 2)
            for x_pix, y_pix in pix:
                x0 = max(0, int(x_pix) - radius_px)
                x1 = min(direction_x.shape[1] - 1, int(x_pix) + radius_px)
                y0 = max(0, int(y_pix) - radius_px)
                y1 = min(direction_x.shape[0] - 1, int(y_pix) + radius_px)
                if x0 > x1 or y0 > y1:
                    continue
                direction_x[y0 : y1 + 1, x0 : x1 + 1] += float(tangent[0])
                direction_y[y0 : y1 + 1, x0 : x1 + 1] += float(tangent[1])
                counts[y0 : y1 + 1, x0 : x1 + 1] += 1.0

    valid_cv = counts > 0
    if valid_cv.any():
        direction_x[valid_cv] /= counts[valid_cv]
        direction_y[valid_cv] /= counts[valid_cv]
        norm = np.sqrt(direction_x**2 + direction_y**2)
        norm_safe = np.maximum(norm, 1e-6)
        direction_x[valid_cv] /= norm_safe[valid_cv]
        direction_y[valid_cv] /= norm_safe[valid_cv]

    direction = np.stack([cv_mask_to_bev(direction_x), cv_mask_to_bev(direction_y)], axis=0).astype(np.float32)
    valid = cv_mask_to_bev(valid_cv.astype(np.uint8)).astype(bool)
    return torch.from_numpy(direction), torch.from_numpy(valid)


def overlay_agents_on_bev(
    bev: np.ndarray,
    source_info: Dict[str, object],
    current_info: Dict[str, object],
) -> np.ndarray:
    out = bev.copy()
    states, names, _ = transform_box_states_to_current(source_info, current_info)
    cv_mask = np.zeros((BEV_PIXEL_WIDTH, BEV_PIXEL_HEIGHT), dtype=np.uint8)
    for label in (BEV_STATIC_LABEL, BEV_VEHICLE_LABEL, BEV_PEDESTRIAN_LABEL):
        cv_mask.fill(0)
        for state, name in zip(states, names):
            cls = classify_b2d_object(name)
            if cls == "vehicle":
                obj_label = BEV_VEHICLE_LABEL
            elif cls == "pedestrian":
                obj_label = BEV_PEDESTRIAN_LABEL
            else:
                if is_b2d_non_collidable_static_object(name):
                    continue
                obj_label = BEV_STATIC_LABEL
            if obj_label != label:
                continue
            if not in_lidar_range(float(state[0]), float(state[1])):
                continue
            rasterize_box(cv_mask, state, value=255)
        entity_mask = cv_mask_to_bev(cv_mask) > 0
        out[entity_mask] = label
    return out


def build_velocity_bev(info: Dict[str, object]) -> torch.Tensor:
    states, names, velocities = current_box_states(info)
    vel_x_cv = np.zeros((BEV_PIXEL_WIDTH, BEV_PIXEL_HEIGHT), dtype=np.float32)
    vel_y_cv = np.zeros((BEV_PIXEL_WIDTH, BEV_PIXEL_HEIGHT), dtype=np.float32)
    for state, name, vel in zip(states, names, velocities):
        if classify_b2d_object(name) not in ("vehicle", "pedestrian"):
            continue
        if not in_lidar_range(float(state[0]), float(state[1])):
            continue
        rasterize_box(vel_x_cv, state, value=float(vel[0]))
        rasterize_box(vel_y_cv, state, value=float(vel[1]))
    vel_x = cv_mask_to_bev(vel_x_cv).astype(np.float32)
    vel_y = cv_mask_to_bev(vel_y_cv).astype(np.float32)
    return torch.from_numpy(np.stack([vel_x, vel_y], axis=0))


def compute_feasible_masks(bev: np.ndarray) -> Tuple[torch.Tensor, torch.Tensor]:
    drivable = ((bev == BEV_ROAD_LABEL) | (bev == BEV_CENTERLINE_LABEL)).astype(np.uint8)
    centerline = bev == BEV_CENTERLINE_LABEL
    if drivable.sum() == 0:
        empty = np.zeros_like(bev, dtype=bool)
        return torch.from_numpy(empty), torch.from_numpy(empty)

    ego_row = 0
    ego_col = (BEV_PIXEL_WIDTH - 1) // 2
    row_end = min(BEV_PIXEL_HEIGHT, 12)
    col_start = max(0, ego_col - 16)
    col_end = min(BEV_PIXEL_WIDTH, ego_col + 17)
    region = drivable[:row_end, col_start:col_end].astype(bool)
    if region.any():
        coords = np.argwhere(region)
        coords[:, 1] += col_start
    else:
        coords = np.argwhere(drivable.astype(bool))

    d2 = (coords[:, 0] - ego_row) ** 2 + (coords[:, 1] - ego_col) ** 2
    seed = coords[int(np.argmin(d2))]
    n_labels, labels = cv2.connectedComponents(drivable, connectivity=8)
    if n_labels <= 1:
        feasible_area = np.zeros_like(bev, dtype=bool)
    else:
        seed_label = labels[int(seed[0]), int(seed[1])]
        feasible_area = (labels == seed_label) & (seed_label > 0)
    feasible_lane = feasible_area & centerline
    return torch.from_numpy(feasible_area), torch.from_numpy(feasible_lane)


def compute_headings(points_xy: np.ndarray, fallback: Optional[np.ndarray] = None) -> np.ndarray:
    if points_xy.shape[0] <= 1:
        return np.zeros((points_xy.shape[0],), dtype=np.float32)
    deltas = points_xy[1:] - points_xy[:-1]
    headings = np.arctan2(deltas[:, 1], deltas[:, 0]).astype(np.float32)
    headings = np.concatenate([headings, headings[-1:]], axis=0)
    if fallback is not None:
        still = np.linalg.norm(deltas, axis=-1) < 1e-3
        if still.any():
            still_idx = np.where(still)[0]
            headings[still_idx] = fallback[still_idx]
    return headings.astype(np.float32)


def build_simple_candidates(
    trajectory: torch.Tensor,
    max_candidates: int,
    lateral_offset_m: float,
    dt: float,
) -> Tuple[torch.Tensor, torch.Tensor]:
    gt = trajectory.detach().cpu().numpy().astype(np.float32)
    num_steps = gt.shape[0]
    candidates = np.zeros((max_candidates, num_steps, 3), dtype=np.float32)
    mask = np.zeros((max_candidates,), dtype=bool)
    if max_candidates <= 0 or num_steps == 0:
        return torch.from_numpy(candidates), torch.from_numpy(mask)

    candidates[0] = gt
    mask[0] = True
    if max_candidates == 1:
        return torch.from_numpy(candidates), torch.from_numpy(mask)

    xy = gt[:, :2]
    headings = gt[:, 2] if gt.shape[1] >= 3 else compute_headings(xy)
    if num_steps > 1:
        speeds = np.linalg.norm(xy[1:] - xy[:-1], axis=-1) / max(dt, 1e-6)
        speeds = np.concatenate([speeds, speeds[-1:]], axis=0).astype(np.float32)
        dyaw = np.asarray([normalize_angle(b - a) for a, b in zip(headings[:-1], headings[1:])])
        yaw_rate = float(np.median(dyaw[: min(3, len(dyaw))]) / max(dt, 1e-6)) if len(dyaw) else 0.0
    else:
        speeds = np.zeros((num_steps,), dtype=np.float32)
        yaw_rate = 0.0

    base_xy = np.zeros_like(xy)
    base_heading = np.zeros((num_steps,), dtype=np.float32)
    base_xy[0] = xy[0]
    base_heading[0] = headings[0] if len(headings) else 0.0
    for i in range(1, num_steps):
        h = float(base_heading[i - 1])
        v = float(speeds[i - 1])
        base_xy[i, 0] = base_xy[i - 1, 0] + v * math.cos(h) * dt
        base_xy[i, 1] = base_xy[i - 1, 1] + v * math.sin(h) * dt
        base_heading[i] = normalize_angle(h + yaw_rate * dt)

    candidates[1] = np.concatenate([base_xy, base_heading[:, None]], axis=1)
    mask[1] = True
    next_idx = 2
    s = np.linspace(0.0, 1.0, num_steps, dtype=np.float32)
    smooth = 3.0 * s**2 - 2.0 * s**3
    normal = np.stack([-np.sin(base_heading), np.cos(base_heading)], axis=1)
    for sign in (1.0, -1.0):
        if next_idx >= max_candidates:
            break
        offset_xy = base_xy + normal * (sign * lateral_offset_m * smooth[:, None])
        offset_heading = compute_headings(offset_xy, fallback=base_heading)
        candidates[next_idx] = np.concatenate([offset_xy, offset_heading[:, None]], axis=1)
        mask[next_idx] = True
        next_idx += 1

    if next_idx < max_candidates:
        slow_xy = xy * 0.5
        slow_heading = compute_headings(slow_xy, fallback=headings)
        candidates[next_idx] = np.concatenate([slow_xy, slow_heading[:, None]], axis=1)
        mask[next_idx] = True

    return torch.from_numpy(candidates), torch.from_numpy(mask)


def interpolate_polyline_by_distance(polyline: np.ndarray, distances: np.ndarray) -> np.ndarray:
    if polyline.shape[0] == 0:
        return np.zeros((len(distances), 2), dtype=np.float32)
    if polyline.shape[0] == 1:
        return np.repeat(polyline[:1], len(distances), axis=0).astype(np.float32)
    seg = polyline[1:] - polyline[:-1]
    seg_len = np.linalg.norm(seg, axis=-1)
    cum = np.concatenate([[0.0], np.cumsum(seg_len)], axis=0)
    max_s = float(cum[-1])
    out = np.zeros((len(distances), 2), dtype=np.float32)
    for i, dist in enumerate(np.clip(distances, 0.0, max_s)):
        j = int(np.searchsorted(cum, dist, side="right") - 1)
        j = max(0, min(j, len(seg_len) - 1))
        denom = max(float(seg_len[j]), 1e-6)
        ratio = float((dist - cum[j]) / denom)
        out[i] = polyline[j] + ratio * seg[j]
    return out.astype(np.float32)


def command_point_local(info: Dict[str, object], key: str) -> Optional[np.ndarray]:
    value = info.get(key)
    if value is None:
        return None
    point = np.asarray(value, dtype=np.float32).reshape(-1)
    if point.shape[0] < 2 or not np.isfinite(point[:2]).all():
        return None
    local = localize_world_xy(point[:2][None], info)
    if local.shape[0] == 0 or not np.isfinite(local[0]).all():
        return None
    return local[0].astype(np.float32)


def select_route_centerline(
    info: Dict[str, object],
    map_infos: Dict[str, object],
    search_radius: float,
    command_weight: float,
) -> Optional[np.ndarray]:
    town_name = str(info.get("town_name", ""))
    map_info = map_infos.get(town_name)
    if map_info is None:
        return None
    world2lidar = np.asarray(info["sensors"]["LIDAR_TOP"]["world2lidar"], dtype=np.float32)
    command = command_point_local(info, "command_far_xy")
    if command is None:
        command = command_point_local(info, "command_near_xy")
    command_norm = None
    if command is not None and np.linalg.norm(command) > 1e-3:
        command_norm = command / max(float(np.linalg.norm(command)), 1e-6)

    best_score = float("inf")
    best_polyline = None
    lane_points = map_info.get("lane_points", [])
    lane_sample_points = map_info.get("lane_sample_points", [])
    lane_types = map_info.get("lane_types", [])
    for lane_idx, (points, lane_type) in enumerate(zip(lane_points, lane_types)):
        if str(lane_type) != "Center":
            continue
        sample_points = lane_sample_points[lane_idx] if lane_idx < len(lane_sample_points) else points
        sample_local = localize_map_points(sample_points, world2lidar)
        if not local_points_in_window(sample_local, front_min=-5.0, front_max=search_radius, lateral_abs=search_radius):
            continue
        local = localize_map_points(points, world2lidar)
        if local.shape[0] < 2:
            continue
        if not local_points_in_window(local, front_min=-5.0, front_max=search_radius, lateral_abs=search_radius):
            continue
        nearest_idx = int(np.argmin(np.linalg.norm(local, axis=-1)))
        if nearest_idx >= local.shape[0] - 1:
            local = local[::-1].copy()
            nearest_idx = int(np.argmin(np.linalg.norm(local, axis=-1)))
        tangent = local[min(nearest_idx + 1, local.shape[0] - 1)] - local[max(nearest_idx - 1, 0)]
        if float(np.linalg.norm(tangent)) < 1e-3:
            continue
        tangent = tangent / max(float(np.linalg.norm(tangent)), 1e-6)
        if tangent[0] < -0.1:
            local = local[::-1].copy()
            nearest_idx = int(np.argmin(np.linalg.norm(local, axis=-1)))
            tangent = -tangent
        if nearest_idx > 0:
            local = local[nearest_idx:].copy()
        if local.shape[0] < 2:
            continue
        heading_penalty = max(0.0, 1.0 - float(tangent[0])) * 10.0
        command_penalty = 0.0
        if command_norm is not None:
            lane_vec = local[min(len(local) - 1, max(1, int(len(local) * 0.25)))] - local[0]
            if np.linalg.norm(lane_vec) > 1e-3:
                lane_vec = lane_vec / max(float(np.linalg.norm(lane_vec)), 1e-6)
                command_penalty = command_weight * max(0.0, 1.0 - float(np.dot(lane_vec, command_norm)))
        score = float(np.linalg.norm(local[0])) + heading_penalty + command_penalty
        if score < best_score:
            best_score = score
            best_polyline = local
    return best_polyline


def trajectory_distances(gt: np.ndarray, dt: float, min_speed: float) -> np.ndarray:
    xy = gt[:, :2]
    if xy.shape[0] == 0:
        return np.zeros((0,), dtype=np.float32)
    step = np.linalg.norm(np.diff(np.concatenate([np.zeros((1, 2), dtype=np.float32), xy], axis=0), axis=0), axis=-1)
    if step.sum() < 1e-3:
        speed = max(float(min_speed), 0.1)
        return (np.arange(1, xy.shape[0] + 1, dtype=np.float32) * speed * max(dt, 1e-6)).astype(np.float32)
    return np.cumsum(step).astype(np.float32)


def make_candidate_from_xy(xy: np.ndarray, fallback_heading: Optional[np.ndarray] = None) -> np.ndarray:
    heading = compute_headings(xy, fallback=fallback_heading)
    return np.concatenate([xy.astype(np.float32), heading[:, None]], axis=1)


def candidate_feasible_ratio(candidate: np.ndarray, feasible_area: torch.Tensor) -> float:
    mask = feasible_area.detach().cpu().numpy().astype(bool)
    cv_mask = bev_to_cv_mask(mask)
    pix = coords_to_cv_pixels(candidate[:, :2].reshape(-1, 1, 2)).reshape(-1, 2)
    inside = []
    for x_pix, y_pix in pix:
        valid = 0 <= x_pix < cv_mask.shape[1] and 0 <= y_pix < cv_mask.shape[0]
        inside.append(bool(valid and cv_mask[int(y_pix), int(x_pix)]))
    return float(np.mean(inside)) if inside else 0.0


def candidate_hits_future_agent(
    candidate: np.ndarray,
    future_agent_boxes: torch.Tensor,
    future_agent_boxes_mask: torch.Tensor,
    margin_m: float,
) -> bool:
    boxes = future_agent_boxes.detach().cpu().numpy()
    masks = future_agent_boxes_mask.detach().cpu().numpy().astype(bool)
    steps = min(candidate.shape[0], boxes.shape[1])
    for step in range(steps):
        point = tuple(float(v) for v in candidate[step, :2])
        for agent_idx in np.where(masks[:, step])[0]:
            corners = boxes[agent_idx, step].astype(np.float32)
            if cv2.pointPolygonTest(corners.reshape(-1, 1, 2), point, measureDist=True) >= -float(margin_m):
                return True
    return False


def append_unique_candidate(
    candidates: List[np.ndarray],
    candidate: np.ndarray,
    min_mean_distance: float,
) -> None:
    if not np.isfinite(candidate).all():
        return
    for existing in candidates:
        dist = np.linalg.norm(existing[:, :2] - candidate[:, :2], axis=-1).mean()
        if float(dist) < min_mean_distance:
            return
    candidates.append(candidate.astype(np.float32))


def build_route_lattice_candidates(
    trajectory: torch.Tensor,
    max_candidates: int,
    lateral_offset_m: float,
    dt: float,
    info: Dict[str, object],
    map_infos: Dict[str, object],
    feasible_area: torch.Tensor,
    future_agent_boxes: torch.Tensor,
    future_agent_boxes_mask: torch.Tensor,
    args: argparse.Namespace,
) -> Tuple[torch.Tensor, torch.Tensor]:
    gt = trajectory.detach().cpu().numpy().astype(np.float32)
    num_steps = gt.shape[0]
    out = np.zeros((max_candidates, num_steps, 3), dtype=np.float32)
    mask = np.zeros((max_candidates,), dtype=bool)
    if max_candidates <= 0 or num_steps == 0:
        return torch.from_numpy(out), torch.from_numpy(mask)

    candidates: List[np.ndarray] = []
    if bool(getattr(args, "candidate_include_gt", True)):
        append_unique_candidate(candidates, gt, min_mean_distance=0.05)

    distances = trajectory_distances(
        gt,
        dt=dt,
        min_speed=float(getattr(args, "candidate_min_speed", 1.0)),
    )
    route = select_route_centerline(
        info,
        map_infos,
        search_radius=float(getattr(args, "candidate_route_search_radius", 60.0)),
        command_weight=float(getattr(args, "candidate_command_weight", 8.0)),
    )
    if route is None:
        return build_simple_candidates(trajectory, max_candidates, lateral_offset_m, dt)

    base_xy = interpolate_polyline_by_distance(route, distances)
    start_offset = -route[:1]
    blend = np.linspace(0.0, 1.0, num_steps, dtype=np.float32)
    blend = 3.0 * blend**2 - 2.0 * blend**3
    base_xy = base_xy + start_offset * (1.0 - blend[:, None])
    base_heading = compute_headings(base_xy, fallback=gt[:, 2] if gt.shape[1] >= 3 else None)
    append_unique_candidate(candidates, make_candidate_from_xy(base_xy, base_heading), min_mean_distance=0.05)

    speed_scales = [0.75, 0.5, 1.2]
    for scale in speed_scales:
        if len(candidates) >= max_candidates:
            break
        scaled_xy = interpolate_polyline_by_distance(route, distances * float(scale))
        scaled_xy = scaled_xy + start_offset * (1.0 - blend[:, None])
        append_unique_candidate(
            candidates,
            make_candidate_from_xy(scaled_xy, base_heading),
            min_mean_distance=float(getattr(args, "candidate_unique_distance", 0.75)),
        )

    normal = np.stack([-np.sin(base_heading), np.cos(base_heading)], axis=1)
    offset_scales = [1.0, -1.0, 0.5, -0.5]
    for sign in offset_scales:
        if len(candidates) >= max_candidates:
            break
        offset_xy = base_xy + normal * (float(sign) * lateral_offset_m * blend[:, None])
        append_unique_candidate(
            candidates,
            make_candidate_from_xy(offset_xy, base_heading),
            min_mean_distance=float(getattr(args, "candidate_unique_distance", 0.75)),
        )

    filtered: List[np.ndarray] = []
    for cand in candidates:
        if bool(getattr(args, "candidate_filter_feasible", True)):
            ratio = candidate_feasible_ratio(cand, feasible_area)
            if ratio < float(getattr(args, "candidate_feasible_ratio", 0.5)):
                continue
        if bool(getattr(args, "candidate_filter_dynamic", False)):
            if candidate_hits_future_agent(
                cand,
                future_agent_boxes=future_agent_boxes,
                future_agent_boxes_mask=future_agent_boxes_mask,
                margin_m=float(getattr(args, "candidate_dynamic_margin", 1.0)),
            ):
                continue
        filtered.append(cand)

    if not filtered:
        filtered = candidates[:1] if candidates else [gt]
    for i, cand in enumerate(filtered[:max_candidates]):
        out[i] = cand
        mask[i] = True
    return torch.from_numpy(out), torch.from_numpy(mask)


def build_debug_pdm_placeholders(
    trajectory: torch.Tensor,
    candidates: torch.Tensor,
    candidates_mask: torch.Tensor,
) -> Dict[str, torch.Tensor]:
    """Finite debug-only score placeholders for checking cache plumbing."""
    num_candidates = int(candidates.shape[0])
    component_targets = torch.full((num_candidates, 6), float("nan"), dtype=torch.float32)
    score_targets = torch.full((num_candidates,), float("nan"), dtype=torch.float32)
    if num_candidates == 0:
        gt_components = torch.tensor([1.0, 1.0, 1.0, 1.0, 1.0, 1.0], dtype=torch.float32)
        return {
            "pdm_score_targets": score_targets,
            "gt_pdm_score": torch.tensor(1.0, dtype=torch.float32),
            "pdm_score_components_candidates": component_targets,
            "gt_pdm_components": gt_components,
        }

    valid = candidates_mask.bool()
    if valid.any():
        dist = torch.linalg.norm(candidates[..., :2] - trajectory[None, :, :2], dim=-1).mean(dim=-1)
        progress = torch.exp(-dist / 3.0).clamp(0.0, 1.0).to(torch.float32)
        score_targets[valid] = progress[valid]
        component_targets[valid] = torch.stack(
            [
                torch.ones_like(progress[valid]),
                torch.ones_like(progress[valid]),
                progress[valid],
                torch.ones_like(progress[valid]),
                torch.ones_like(progress[valid]),
                torch.ones_like(progress[valid]),
            ],
            dim=-1,
        )

    gt_components = torch.tensor([1.0, 1.0, 1.0, 1.0, 1.0, 1.0], dtype=torch.float32)
    return {
        "pdm_score_targets": score_targets,
        "gt_pdm_score": torch.tensor(1.0, dtype=torch.float32),
        "pdm_score_components_candidates": component_targets,
        "gt_pdm_components": gt_components,
    }


def build_cache_entry(
    infos: Sequence[Dict[str, object]],
    idx: int,
    split: str,
    b2d_root: Path,
    map_infos: Dict[str, object],
    args: argparse.Namespace,
) -> Optional[Tuple[str, Dict[str, object], Dict[str, object]]]:
    info = infos[idx]
    trajectory = build_future_trajectory(
        infos,
        idx=idx,
        sample_interval=args.sample_interval,
        future_frames=args.future_frames,
        max_translation_m=args.max_trajectory_translation,
        max_step_m=args.max_trajectory_step,
    )
    if trajectory is None:
        return None

    future_idx = idx + args.future_frames * args.sample_interval
    future_info = infos[future_idx] if future_idx < len(infos) and is_same_log(info, infos[future_idx]) else info

    static_bev = build_static_map_bev(info, map_infos)
    bev_semantic_map = overlay_agents_on_bev(static_bev, source_info=info, current_info=info)
    future_bev_semantic_map = overlay_agents_on_bev(static_bev, source_info=future_info, current_info=info)
    feasible_area_mask, feasible_lane_mask = compute_feasible_masks(bev_semantic_map)
    agent_states, agent_labels = build_agent_targets(info, max_agents=args.max_agents)
    future_agent_boxes, future_agent_boxes_mask = build_future_agent_boxes(
        infos,
        idx=idx,
        sample_interval=args.sample_interval,
        future_frames=args.future_frames,
        max_future_agents=args.max_future_agents,
        range_m=args.future_agent_range,
    )
    if args.candidate_mode == "route_lattice":
        candidates, candidates_mask = build_route_lattice_candidates(
            trajectory=trajectory,
            max_candidates=args.num_candidates,
            lateral_offset_m=args.candidate_lateral_offset,
            dt=args.trajectory_dt,
            info=info,
            map_infos=map_infos,
            feasible_area=feasible_area_mask,
            future_agent_boxes=future_agent_boxes,
            future_agent_boxes_mask=future_agent_boxes_mask,
            args=args,
        )
    else:
        candidates, candidates_mask = build_simple_candidates(
            trajectory=trajectory,
            max_candidates=args.num_candidates,
            lateral_offset_m=args.candidate_lateral_offset,
            dt=args.trajectory_dt,
        )
    wrong_direction_enabled, scenario_type = infer_wrong_direction_enabled(info, args)

    token = safe_token(split, idx, info)
    features: Dict[str, object] = {
        "camera_feature": build_camera_feature(
            info,
            b2d_root,
            stitch_mode=args.camera_stitch_mode,
            side_crop_ratio=args.camera_side_crop_ratio,
            side_overlap_ratio=args.camera_side_overlap_ratio,
        ),
        "lidar_feature": build_lidar_feature(
            info,
            b2d_root,
            mode=args.lidar_mode,
            coordinate_mode=args.lidar_coordinate_mode,
            height_mode=args.lidar_height_mode,
            pixels_per_meter=args.lidar_pixels_per_meter,
            hist_max_per_pixel=args.lidar_hist_max_per_pixel,
            max_height_lidar=args.lidar_max_height,
            lidar_split_height=args.lidar_split_height,
            auto_min_points=args.lidar_auto_min_points,
        ),
        "status_feature": build_status_feature(info),
        "ego_history": build_ego_history(
            infos,
            idx=idx,
            sample_interval=args.sample_interval,
            history_frames=args.history_frames,
        ),
    }
    targets: Dict[str, object] = {
        "trajectory": trajectory,
        "agent_states": agent_states,
        "agent_labels": agent_labels,
        "future_agent_boxes": future_agent_boxes,
        "future_agent_boxes_mask": future_agent_boxes_mask,
        "bev_semantic_map": torch.from_numpy(bev_semantic_map.astype(np.float32)),
        "token": token,
        "future_bev_semantic_map": torch.from_numpy(future_bev_semantic_map.astype(np.float32)),
        "feasible_area_mask": feasible_area_mask.bool(),
        "feasible_lane_mask": feasible_lane_mask.bool(),
        "velocity_bev": build_velocity_bev(info),
        "trajectory_candidates": candidates,
        "trajectory_candidates_mask": candidates_mask,
        "wrong_direction_check_enabled": torch.tensor(wrong_direction_enabled, dtype=torch.bool),
        "b2d_scenario_type": scenario_type,
        "b2d_index": idx,
        "b2d_split": split,
        "folder": str(info.get("folder", "")),
        "frame_idx": int(info.get("frame_idx", idx)),
        "town_name": str(info.get("town_name", "")),
        "lidar2world": torch.from_numpy(diffusiondrive_lidar2world(info)),
        "b2d_lidar2world": torch.from_numpy(
            np.linalg.inv(np.asarray(info["sensors"]["LIDAR_TOP"]["world2lidar"], dtype=np.float32)).astype(np.float32)
        ),
    }
    if args.write_lane_direction_bev:
        lane_direction_bev, lane_direction_mask = build_lane_direction_bev(
            info,
            map_infos,
            radius_m=args.lane_direction_radius_m,
            search_radius=args.candidate_route_search_radius,
        )
        targets["lane_direction_bev"] = lane_direction_bev
        targets["lane_direction_mask"] = lane_direction_mask.bool()
    if args.write_debug_pdm_placeholders:
        targets.update(build_debug_pdm_placeholders(trajectory, candidates, candidates_mask))
    return token, features, targets


def iter_indices(length: int, limit: int, stride: int) -> Iterable[int]:
    count = 0
    for idx in range(0, length, max(1, stride)):
        if limit > 0 and count >= limit:
            break
        yield idx
        count += 1


def init_worker(
    infos: Sequence[Dict[str, object]],
    map_infos: Dict[str, object],
    args: argparse.Namespace,
    split: str,
    b2d_root: str,
    cache_root: str,
) -> None:
    global _WORKER_INFOS
    global _WORKER_MAP_INFOS
    global _WORKER_ARGS
    global _WORKER_SPLIT
    global _WORKER_B2D_ROOT
    global _WORKER_CACHE_ROOT
    _WORKER_INFOS = infos
    _WORKER_MAP_INFOS = map_infos
    _WORKER_ARGS = args
    _WORKER_SPLIT = split
    _WORKER_B2D_ROOT = Path(b2d_root)
    _WORKER_CACHE_ROOT = Path(cache_root)


def process_index_worker(idx: int) -> Tuple[str, int, str]:
    try:
        entry = build_cache_entry(
            infos=_WORKER_INFOS,
            idx=idx,
            split=_WORKER_SPLIT,
            b2d_root=_WORKER_B2D_ROOT,
            map_infos=_WORKER_MAP_INFOS,
            args=_WORKER_ARGS,
        )
    except FileNotFoundError as exc:
        message = str(exc)
        missing_lidar = "lidar" in message.lower() or message.lower().endswith(".laz")
        if missing_lidar:
            if not _WORKER_ARGS.skip_missing_lidar:
                raise
        elif not _WORKER_ARGS.skip_missing_images:
            raise
        return "skipped", idx, str(exc)
    if entry is None:
        return "skipped", idx, "invalid_future"
    token, features, targets = entry
    token_dir = _WORKER_CACHE_ROOT / _WORKER_SPLIT / token
    dump_feature_target_to_pickle(token_dir / "transfuser_feature.gz", features)
    dump_feature_target_to_pickle(token_dir / "transfuser_target.gz", targets)
    return "written", idx, token


def process_split(split: str, args: argparse.Namespace) -> None:
    infos_root = Path(args.infos_root)
    b2d_root = Path(args.b2d_root)
    cache_root = Path(args.cache_root)
    info_path = infos_root / f"b2d_infos_{split}.pkl"
    map_path = infos_root / "b2d_map_infos.pkl"
    if not info_path.is_file():
        raise FileNotFoundError(f"Missing B2D infos: {info_path}")
    if not map_path.is_file():
        raise FileNotFoundError(f"Missing B2D map infos: {map_path}")

    infos = load_pickle(info_path)
    map_infos = load_pickle(map_path)
    written = 0
    skipped = 0
    split_dir = cache_root / split
    split_dir.mkdir(parents=True, exist_ok=True)

    indices = list(iter_indices(len(infos), limit=args.limit, stride=args.stride))
    if args.workers > 1:
        with mp.Pool(
            processes=args.workers,
            initializer=init_worker,
            initargs=(infos, map_infos, args, split, str(b2d_root), str(cache_root)),
        ) as pool:
            for status, _, _ in tqdm(
                pool.imap_unordered(process_index_worker, indices),
                total=len(indices),
                desc=f"caching {split}",
            ):
                if status == "written":
                    written += 1
                else:
                    skipped += 1
    else:
        init_worker(infos, map_infos, args, split, str(b2d_root), str(cache_root))
        for idx in tqdm(indices, desc=f"caching {split}"):
            status, _, _ = process_index_worker(idx)
            if status == "written":
                written += 1
            else:
                skipped += 1

    print(f"{split}: wrote {written} samples to {split_dir}, skipped {skipped}")


def parse_args() -> argparse.Namespace:
    default_cache_root = os.environ.get("NAVSIM_EXP_ROOT")
    if default_cache_root:
        default_cache_root = str(Path(default_cache_root) / "b2d_diffusiondrive_cache")
    else:
        default_cache_root = "exp/b2d_diffusiondrive_cache"

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--b2d-root", default="Bench2DriveZoo/data/bench2drive")
    parser.add_argument("--infos-root", default="Bench2DriveZoo/data/infos")
    parser.add_argument("--cache-root", default=default_cache_root)
    parser.add_argument("--splits", nargs="+", default=["train", "val"], choices=["train", "val"])
    parser.add_argument("--sample-interval", type=int, default=5)
    parser.add_argument("--future-frames", type=int, default=6)
    parser.add_argument("--history-frames", type=int, default=4)
    parser.add_argument("--trajectory-dt", type=float, default=0.5)
    parser.add_argument(
        "--max-trajectory-translation",
        type=float,
        default=120.0,
        help="Skip samples whose future ego trajectory leaves this local-radius bound in meters. <=0 disables.",
    )
    parser.add_argument(
        "--max-trajectory-step",
        type=float,
        default=60.0,
        help="Skip samples whose per-frame future ego displacement exceeds this meter threshold. <=0 disables.",
    )
    parser.add_argument("--max-agents", type=int, default=30)
    parser.add_argument("--max-future-agents", type=int, default=64)
    parser.add_argument(
        "--future-agent-range",
        type=float,
        default=48.0,
        help="Keep future dynamic boxes whose center is within this local range in meters. <=0 keeps all before max cap.",
    )
    parser.add_argument("--num-candidates", type=int, default=5)
    parser.add_argument(
        "--candidate-mode",
        choices=["simple", "route_lattice"],
        default="route_lattice",
        help="simple keeps the original debug candidates; route_lattice uses B2D map centerlines and command points.",
    )
    parser.add_argument("--candidate-include-gt", action="store_true", default=True)
    parser.add_argument("--no-candidate-include-gt", dest="candidate_include_gt", action="store_false")
    parser.add_argument("--candidate-lateral-offset", type=float, default=3.5)
    parser.add_argument("--candidate-route-search-radius", type=float, default=60.0)
    parser.add_argument("--candidate-command-weight", type=float, default=8.0)
    parser.add_argument("--candidate-min-speed", type=float, default=1.0)
    parser.add_argument("--candidate-unique-distance", type=float, default=0.75)
    parser.add_argument("--candidate-filter-feasible", action="store_true", default=True)
    parser.add_argument("--no-candidate-filter-feasible", dest="candidate_filter_feasible", action="store_false")
    parser.add_argument("--candidate-feasible-ratio", type=float, default=0.5)
    parser.add_argument("--candidate-filter-dynamic", action="store_true", default=False)
    parser.add_argument("--candidate-dynamic-margin", type=float, default=1.0)
    parser.add_argument(
        "--b2d-routes-file",
        type=Path,
        default=None,
        help="Optional bench2drive route XML. Used only to disable wrong-direction labels on allowed scenarios.",
    )
    parser.add_argument(
        "--wrong-direction-disabled-scenarios",
        nargs="*",
        default=list(B2D_WRONG_DIRECTION_DISABLED_SCENARIOS),
    )
    parser.add_argument(
        "--write-lane-direction-bev",
        action="store_true",
        help="Write lane_direction_bev/lane_direction_mask for B2D scorer wrong-lane supervision. Disable for fast proposal-only cache tests.",
    )
    parser.add_argument("--lane-direction-radius-m", type=float, default=1.0)
    parser.add_argument(
        "--camera-stitch-mode",
        choices=["b2d_mid", "b2d_outer", "b2d_inner", "navsim_center", "front_only"],
        default="b2d_mid",
        help="How to build the 3-camera front panorama. navsim_center preserves the old B2D debug behavior.",
    )
    parser.add_argument(
        "--camera-side-crop-ratio",
        type=float,
        default=192.0 / 1024.0,
        help="Width ratio kept from CAM_FRONT_LEFT/RIGHT when camera-stitch-mode is not front_only.",
    )
    parser.add_argument(
        "--camera-side-overlap-ratio",
        type=float,
        default=192.0 / 1024.0,
        help="Inner side-camera width skipped before b2d_mid stitching. Keep this fixed when increasing side crop width.",
    )
    parser.add_argument(
        "--lidar-mode",
        choices=["histogram", "zeros"],
        default="histogram",
        help="How to build lidar_feature. histogram reads Bench2Drive lidar .laz files; zeros is only for smoke tests.",
    )
    parser.add_argument(
        "--lidar-coordinate-mode",
        choices=["b2d_lidar", "front_left", "identity"],
        default="front_left",
        help="Coordinate conversion for raw B2D lidar .laz points before rasterization.",
    )
    parser.add_argument(
        "--lidar-height-mode",
        choices=["auto", "above", "all"],
        default="auto",
        help="Height filtering before rasterization. auto falls back to all points if above-ground points are too sparse.",
    )
    parser.add_argument("--lidar-pixels-per-meter", type=float, default=4.0)
    parser.add_argument("--lidar-hist-max-per-pixel", type=float, default=5.0)
    parser.add_argument("--lidar-max-height", type=float, default=100.0)
    parser.add_argument("--lidar-split-height", type=float, default=0.2)
    parser.add_argument("--lidar-auto-min-points", type=int, default=256)
    parser.add_argument("--workers", type=int, default=1)
    parser.add_argument("--limit", type=int, default=0, help="Debug only: max samples per split. 0 means all.")
    parser.add_argument("--stride", type=int, default=1, help="Debug only: cache every Nth sample.")
    parser.add_argument(
        "--write-debug-pdm-placeholders",
        action="store_true",
        help="Debug only: write finite PDM-like placeholder fields. Do not use as real B2D score supervision.",
    )
    parser.add_argument("--skip-missing-images", action="store_true", default=False)
    parser.add_argument("--no-skip-missing-images", dest="skip_missing_images", action="store_false")
    parser.add_argument("--skip-missing-lidar", action="store_true", default=False)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    args.route_scenario_by_id = load_route_scenarios(args.b2d_routes_file)
    for split in args.splits:
        process_split(split, args)


if __name__ == "__main__":
    main()
