_target_: navsim.agents.diffusiondrive_orig.transfuser_agent.TransfuserAgent
_convert_: 'all'

config:
  _target_: navsim.agents.diffusiondrive_orig.transfuser_config.TransfuserConfig
  _convert_: 'all'

  trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: 'all'
    time_horizon: 4
    interval_length: 0.5

  latent: False
  plan_anchor_path: exp/anchors/kmeans_navsim_traj_20.npy

checkpoint_path: null
lr: 2e-4
